version: '3.8'

services:
  # Base de datos MySQL
  db:
    build: ./database
    container_name: ob_votacion_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: micontraseñasecreta_root
      MYSQL_DATABASE: ObligatorioBD2
      MYSQL_USER: usuario_bd
      MYSQL_PASSWORD: Xudmyg-sahjy3-jokroc
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/estructura.sql:/docker-entrypoint-initdb.d/estructura.sql

  # Backend Node.js
  backend:
    build: ./backend
    container_name: ob_votacion_node
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: usuario_bd
      DB_PASSWORD: Xudmyg-sahjy3-jokroc
      DB_NAME: ObligatorioBD2
      DB_PORT: 3306
    depends_on:
      - db

  # Frontend React + Vite
  frontend:
    build: ./frontend
    container_name: ob_votacion_react
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: