version: '3.8'

services:
  # Container para MySql / Base de datos
  db:
    build: ./database
    container_name: ob_votacion_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: micontraseñasecreta_root
      MYSQL_DATABASE: ObligatorioBD2
      MYSQL_USER: usuario_bd
      MYSQL_PASSWORD: Xudmyg-sahjy3-jokroc
    ports:
      - "3306:3306"
    volumes:
      # Crea un volumen para que los datos de la base de datos persistan.
      - mysql_data:/var/lib/mysql

  # Container para el Backend (Node.js)
  backend:
    build: ./backend
    container_name: ob_votacion_node
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Variables de entorno para que el backend se conecte a MySQL.
      # Usamos db como host para que Docker Compose resuelva el nombre del servicio.
      DB_HOST: db
      DB_USER: usuario_bd
      DB_PASSWORD: Xudmyg-sahjy3-jokroc
      DB_NAME: ObligatorioBD2
      DB_PORT: 3306
    depends_on:
      # Esto asegura que el backend espere a que la base de datos esté lista antes de iniciar.
      - db

  # Container para el Frontend (React)
  frontend:
    build: ./frontend
    container_name: ob_votacion_react
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:

